### PR TITLE
[Issue-169] Require contact_preference

### PR DESCRIPTION
**Pull request by reginafcompton**
## Description

The AHS newsletter editor has requested that members are required (moving forward) to indicate how they want to receive their newsletter (print, email, or both). 

Changes include:
* add ~`blank=True`~ `blank=False` to the `Member.contact_preference`; this no longer allows forms to pass a "blank" value for `Member.contact_prference`, i.e., no more empty strings.
* include a dropdown for contact_preference in the Join form

## Manual Testing

Three forms support the creation and editing of members:

**One. Join – http://127.0.0.1:8000/join/** This form now includes and requires contact_preference info.
Screenshot 2023-10-09 at 11 53 48 AM

**Two. The "update information" form, accessible via the profile page – http://127.0.0.1:8000/profile/** This form always included contact_preference, but now it requires it.

**Three. The super admin view, which allows adding and editing members.** This form always included contact_preference, but now it requires it. _This could introduce some tedium if an admin needs to edit an existing member's data, since the admin will need to know the member's contact preference, if it was not already populated._

Screenshot 2023-10-09 at 11 51 21 AM

Closes https://github.com/americanhandelsociety/americanhandelsociety-members/issues/169

### CODE REVIEW

**Comment by reginafcompton** [comment]
@ecedmondson - THIS IS NOT URGENT. You can review when you are state-side! Again: this is not urgent; please continue eating ham.

**Comment by ecedmondson** [comment]
Thanks for clarifying that it is not urgent, @reginafcompton...however, I did not even have a laptop with me so I could not have helped anyway. I am back in Houston and will try to take a look at this this evening....without ham unfortunately...

**Comment by ecedmondson** [comment]
> add blank=True...

I think you mean either `add blank=False` or `remove blank=True`. Either way of expressing this idea, the code already does so.

**Review by ecedmondson — APPROVED** [review]
I pulled locally and tested joining/updating etc.

**Comment by ecedmondson** [comment]
Happy to approve. I think I have neglected checking for new issues in the issues tab of this project...

**Comment by reginafcompton** [comment]
Thank you @ecedmondson ! I'll likely get this merged and deployed before the end of the week.

**Pull request merged**
