### PR TITLE
Issue 172 Part B: time machine 

### PR DESCRIPTION
**Pull request by ecedmondson**
I don't particularly like putting package changes in feature PRs. 

What do you think?

### CODE REVIEW

**Review by reginafcompton — APPROVED** [review]
MAGIC! Thank you.

**Comment by ecedmondson** [comment]
Oh actually...I am still sort of testing this flow locally. I assumed you were not online. 

On that note, I forgot to update the paypal flow. My personal computer also auto-auths to Paypal. Anyway, I think I might have accidentally just become a member. Which is fine I guess.

**Comment by reginafcompton** [comment]
> Anyway, I think I might have accidentally just become a member.

I just checked: no Emily in the Handel society. If you are testing locally, it will redirect to a sandbox, which should not take your money.

**Comment by ecedmondson** [comment]
> I just checked: no Emily in the Handel society. If you are testing locally, it will redirect to a sandbox, which should not take your money.

Yeah, I figured that out the second time when I went back. Incidentally, I have lost the login credentials so I can't test that flow, but I did notice that django-paypal didn't upgrade versions. 

Are you worried about any of the other package updates in here?

**Comment by reginafcompton** [comment]
> Are you worried about any of the other package updates in here?

Nope. I think this seems safe. I also QA staging (typical flows: sign up, login, email reminder) before I do a production deployment. (And yes: I need to look up the Paypal credentials, again.)

**Comment by ecedmondson** [comment]
> Nope. I think this seems safe. I also QA staging (typical flows: sign up, login, email reminder) before I do a production deployment. (And yes: I need to look up the Paypal credentials, again.)

I am going to rebase the other PR with this if you want to wait.

**Pull request merged**
